apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-management
  template:
    metadata:
      labels:
        app: container-management
    spec:
      containers:
      - name: container-management
        image: yourdockerhub/container-management:latest
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: container-management
spec:
  selector:
    app: container-management
  ports:
  - port: 8083
    targetPort: 8083
