apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-registration
  template:
    metadata:
      labels:
        app: item-registration
    spec:
      containers:
      - name: item-registration
        image: yourdockerhub/item-registration:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: item-registration
spec:
  selector:
    app: item-registration
  ports:
  - port: 8081
    targetPort: 8081
