server:
  port: 8083

spring:
  application:
    name: container-management
  datasource:
    url: jdbc:postgresql://localhost:5432/container_management
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: container-management-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    config:
      enabled: false  # Set to true in production with proper config server
      fail-fast: false

kafka:
  topics:
    item-registered: item-registered
    container-status: container-status
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.micrologistics: INFO
    org.springframework.web: INFO
    org.springframework.data: INFO
    org.springframework.kafka: INFO

info:
  application:
    name: ${spring.application.name}
    description: Container Management Service for MicroLogistics
    version: 1.0.0
