server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yourusername/micrologistics-config
          default-label: main
          clone-on-start: true
          # Uncomment the following for local file system repository (development use)
          # native:
          #   search-locations: file:///path/to/local/config-repo
  security:
    user:
      name: config
      password: password
  profiles:
    active: git  # Change to 'native' for local file system repository

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    env:
      enabled: true

info:
  application:
    name: ${spring.application.name}
    description: MicroLogistics Configuration Server
    version: 1.0.0
